wms-server:
    name: geomet-weather
    url: ${GEOMET_MAPPROXY_CACHE_WMS}
    layers: [
        RADAR_1KM_RRAI,
        RADAR_1KM_RSNO,
        RADAR_COVERAGE_RRAI,
        RADAR_COVERAGE_RRAI.INV,
        RADAR_COVERAGE_RSNO,
        RADAR_COVERAGE_RSNO.INV,
        Radar_1km_dBZ-Extrapolation,
        Radar_1km_SnowPrecipRate-Extrapolation,
        Radar_1km_RainPrecipRate-Extrapolation,
        Radar-Coverage_SfcPrecipType,
        Radar-Coverage_SfcPrecipType-Inverted,
        Radar_1km_SfcPrecipType
    ]
